# Generated by Django 5.1.5 on 2025-03-05 11:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('college_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, validators=[accounts.models.validate_email_format])),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
