# Generated by Django 5.1.5 on 2025-02-05 14:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, validators=[accounts.models.validate_email_format]),
        ),
    ]
