# Generated by Django 5.1.5 on 2025-03-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='{% static "images/default.png" %}', null=True, upload_to='profile_images/'),
        ),
    ]
