# Generated by Django 5.1.5 on 2025-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('academic_batch', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='{% static "images/default.png" %}', null=True, upload_to='faculty_images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
