# Generated by Django 5.1.5 on 2025-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('hi_tea', models.TextField()),
                ('dinner', models.TextField()),
            ],
            options={
                'verbose_name': 'Mess Schedule',
                'verbose_name_plural': 'Mess Schedules',
            },
        ),
    ]
