# Generated by Django 5.1.5 on 2025-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_messschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('time_to_board', models.CharField(max_length=10)),
                ('last_time_to_board', models.CharField(max_length=10)),
                ('no_of_buses', models.IntegerField()),
                ('batch', models.CharField(max_length=50)),
                ('no_of_students', models.IntegerField()),
                ('lunch_venue', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
