# Generated by Django 5.1.5 on 2025-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_busschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busschedule',
            name='lunch_venue',
        ),
    ]
