# Generated by Django 5.1.5 on 2025-03-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_busschedule_lunch_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('room', models.CharField(max_length=20)),
                ('room_capacity', models.IntegerField()),
                ('actual_students', models.IntegerField()),
                ('course_code', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
