# Generated by Django 5.1.5 on 2025-04-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='actual_students',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='room_capacity',
        ),
    ]
