# Generated by Django 5.1.5 on 2025-03-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('credits', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('previous_spi', models.FloatField()),
                ('previous_cpi', models.FloatField()),
                ('semester_applying_for', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=2)),
                ('college_fee_proof', models.FileField(upload_to='fee_documents/')),
                ('hostel_fee_proof', models.FileField(upload_to='fee_documents/')),
                ('loan_refund_form', models.FileField(blank=True, null=True, upload_to='fee_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('selected_courses', models.ManyToManyField(help_text='Selected courses', to='course_registration.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.student')),
            ],
        ),
    ]
