# Generated by Django 5.1.5 on 2025-03-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch_name',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('CSE/IT', 'Computer Science or Information Technology')], default='CSE/IT', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='branch_name',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('CSE/IT', 'Computer Science or Information Technology')], default='CSE/IT', max_length=10),
        ),
    ]
