# Generated by Django 5.1.5 on 2025-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='open_electives',
            field=models.TextField(blank=True, help_text='Comma-separated list of open electives', null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='program_electives',
            field=models.TextField(blank=True, help_text='Comma-separated list of program electives', null=True),
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='selected_courses',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='selected_courses',
            field=models.ManyToManyField(help_text='Selected courses', to='course_registration.course'),
        ),
    ]
