# Generated by Django 5.1.5 on 2025-02-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0003_alter_studentregistration_open_electives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='open_electives',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='program_electives',
        ),
    ]
