# Generated by Django 5.1.5 on 2025-03-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0003_facultyadvisor_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_registration.facultyadvisor'),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_registration.facultyadvisor'),
        ),
    ]
