# Generated by Django 5.1.5 on 2025-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0004_studentregistration_faculty_alter_enrolled_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='selected_courses',
            field=models.ManyToManyField(to='course_registration.course'),
        ),
    ]
