# Generated by Django 5.1.5 on 2025-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0005_alter_studentregistration_selected_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(max_length=15),
        ),
    ]
