# Generated by Django 5.1.5 on 2025-03-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_faculty'),
        ('course_registration', '0006_alter_course_course_code_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty'),
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='college_id',
        ),
        migrations.DeleteModel(
            name='FacultyAdvisor',
        ),
    ]
