# Generated by Django 5.1.5 on 2025-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0007_alter_enrolled_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Issues', 'Issues'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='In Progress', max_length=50),
        ),
    ]
