# Generated by Django 5.1.5 on 2025-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0008_studentregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='message',
            field=models.TextField(blank=True, help_text='Message from faculty regarding the registration status.', max_length=500, null=True),
        ),
    ]
