# Generated by Django 5.1.5 on 2025-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0009_studentregistration_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
