# Generated by Django 5.1.5 on 2025-03-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0010_studentregistration_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='is_submitted',
        ),
    ]
