# Generated by Django 5.1.5 on 2025-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0011_remove_studentregistration_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='grade_sheet',
            field=models.FileField(blank=True, help_text='Upload your grade sheet (PDF format recommended).', null=True, upload_to='fee_documents/'),
        ),
    ]
